version: 2
jobs:
  test:
    working_directory: ~/feed
    docker:
      - image: circleci/node:dubnium
      - image: ibmcom/cloudant-developer
      - image: redis
    environment:
      NODE_ENV: development
      COUCH_PROTOCOL: 'http:'
      COUCH_HOST: 127.0.0.1
      COUCH_PORT: 5984
      COUCH_ADMIN_USERNAME: admin
      COUCH_ADMIN_PASSWORD: pass
      COUCH_AUTH_DB: _users
      DB_NAME: scienceai
    steps:
      - checkout
      - run: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
            - v2-node_modules-
      - run: npm install
      - save_cache:
          key: v2-node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
      - persist_to_workspace:
          root: ~/feed
          paths: .

  publish:
    working_directory: ~/feed
    docker:
      - image: circleci/node:dubnium
    steps:
      - attach_workspace:
          at: ~/feed
      - run:
          name: Authenticate with registry
          command: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:  # required since `publish` has tag filters AND requires `test`
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
